const MIN_PEOPLE=2,MAX_PEOPLE=20;
const state={groups:[],activeGroupId:null};
let draftPeople=["",""];let splitSharesCustomized=false;let manualShareIds=new Set();let expenseDate=null;let expensePeriodName="morning";let editingExpenseId=null;let pendingDeleteExpenseId=null;let pendingEndTrip=false;let selectedDayDate=null;let carouselDates=[];let swipeStartX=null;
const $=selector=>document.querySelector(selector);
const money=cents=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(cents/100);
function parseMoneyToCents(value){const cleaned=String(value??"").replace(/[,₱\s]/g,"");if(!/^\d*(\.\d{0,2})?$/.test(cleaned)||cleaned==="")return NaN;return Math.round(Number(cleaned)*100)}
function formatMoneyText(value){const raw=String(value??"").replace(/,/g,"").replace(/[^\d.]/g,"");if(!raw)return"";const hasDecimal=raw.includes("."),parts=raw.split("."),integer=(parts.shift()||"0").replace(/^0+(?=\d)/,"")||"0",decimals=parts.join("").slice(0,2),formatted=integer.replace(/\B(?=(\d{3})+(?!\d))/g,",");return hasDecimal?`${formatted}.${decimals}`:formatted}
function formatCentsForInput(cents){return (cents/100).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}
function attachMoneyInput(input){input.addEventListener("input",()=>{input.value=formatMoneyText(input.value)});input.addEventListener("blur",()=>{const cents=parseMoneyToCents(input.value);if(Number.isFinite(cents))input.value=formatCentsForInput(cents)})}
const makeId=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>toDateKey(new Date());
function toDateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function fromDateKey(key){const [year,month,day]=key.split("-").map(Number);return new Date(year,month-1,day)}
function addDays(key,count){const date=fromDateKey(key);date.setDate(date.getDate()+count);return toDateKey(date)}
function dayDistance(from,to){return Math.round((fromDateKey(to)-fromDateKey(from))/86400000)}
function formatDate(key,options={weekday:"long",month:"short",day:"numeric"}){return new Intl.DateTimeFormat("en-PH",options).format(fromDateKey(key))}
function currentGroup(){return state.groups.find(group=>group.id===state.activeGroupId)}

const dataStore={key:"anti-buraot:v2",legacyKey:"anti-buraot:v1",load(){try{const current=JSON.parse(localStorage.getItem(this.key));if(current&&Array.isArray(current.groups))return current;const legacy=JSON.parse(localStorage.getItem(this.legacyKey));if(legacy&&legacy.groupName&&Array.isArray(legacy.members)){const start=today();return{groups:[{id:makeId(),name:legacy.groupName,members:legacy.members,expenses:(legacy.expenses||[]).map(expense=>({...expense,date:expense.date||start})),tripStartDate:start,testOffset:0}]}}}catch{}return{groups:[]}},save(){try{localStorage.setItem(this.key,JSON.stringify({groups:state.groups}));return true}catch{return false}}};
function saveState(){dataStore.save()}
function showError(selector,message){const element=$(selector);element.textContent=message;element.hidden=false}
function hideError(selector){$(selector).hidden=true}
function escapeHtml(value){const element=document.createElement("span");element.textContent=value;return element.innerHTML}

function renderPeopleInputs(){const list=$("#people-list");list.innerHTML="";draftPeople.forEach((name,index)=>{const row=document.createElement("div");row.className="member-row";row.innerHTML=`<span class="member-avatar" aria-hidden="true">👤</span><input class="input" aria-label="Member ${index+1} name" maxlength="40" autocomplete="off" placeholder="${index===0?"Your name":`Member ${index+1} name`}">${draftPeople.length>MIN_PEOPLE?`<button class="remove-member" type="button" aria-label="Remove member ${index+1}">×</button>`:"<span></span>"}`;const input=row.querySelector("input");input.value=name;input.addEventListener("input",event=>{draftPeople[index]=event.target.value;updatePeopleCount();hideError("#group-error")});const remove=row.querySelector(".remove-member");if(remove)remove.addEventListener("click",()=>{draftPeople.splice(index,1);renderPeopleInputs()});list.appendChild(row)});if(draftPeople.length<MAX_PEOPLE){const add=document.createElement("button");add.className="add-member-button";add.type="button";add.textContent="+ Add another member";add.addEventListener("click",()=>{draftPeople.push("");renderPeopleInputs();const inputs=list.querySelectorAll("input");inputs[inputs.length-1].focus()});list.appendChild(add)}updatePeopleCount()}
function updatePeopleCount(){$("#completion").textContent=`${draftPeople.filter(name=>name.trim()).length} of ${draftPeople.length} named`}

function showSetup(){draftPeople=["",""];$("#group-form").reset();renderPeopleInputs();$("#cancel-group").hidden=!state.groups.length;$("#groups-screen").hidden=true;$("#group-screen").hidden=true;$("#setup-screen").hidden=false;$("#group-name").focus()}
function showGroups(){state.activeGroupId=null;renderGroups();$("#setup-screen").hidden=true;$("#group-screen").hidden=true;$("#groups-screen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function createGroup(event){event.preventDefault();const name=$("#group-name").value.trim();const names=draftPeople.map(person=>person.trim());if(!name)return showError("#group-error","Give your group a name first.");if(names.some(person=>!person))return showError("#group-error","Add a name for every member.");if(new Set(names.map(person=>person.toLowerCase())).size!==names.length)return showError("#group-error","Each member needs a unique name.");state.groups.unshift({id:makeId(),name,members:names.map(member=>({id:makeId(),name:member})),expenses:[],tripStartDate:null,testOffset:0});saveState();showGroups()}
function renderGroups(){const list=$("#groups-list");list.innerHTML=state.groups.map(group=>{const posted=group.expenses.filter(expense=>!expense.isDraft),draftCount=group.expenses.length-posted.length,total=posted.reduce((sum,expense)=>sum+expense.amount,0);const status=group.tripEndDate?`Ended ${formatDate(group.tripEndDate,{month:"short",day:"numeric",year:"numeric"})}`:group.tripStartDate?`Started ${formatDate(group.tripStartDate,{month:"short",day:"numeric",year:"numeric"})}`:"Not started";return `<article class="group-card"><div class="group-card-icon">${escapeHtml(group.name.charAt(0).toUpperCase())}</div><div class="group-card-copy"><h2>${escapeHtml(group.name)}</h2><p>${group.members.length} members · ${status}</p>${group.expenses.length?`<small>${posted.length} ${posted.length===1?"expense":"expenses"} · ${money(total)}${draftCount?` · ${draftCount} ${draftCount===1?"draft":"drafts"}`:""}</small>`:""}</div><button class="start-trip-button" type="button" data-group-id="${group.id}"><span>${group.tripStartDate?"↗":"▶"}</span>${group.tripEndDate?"View trip":group.tripStartDate?"Open trip":"Start trip"}</button></article>`}).join("");list.querySelectorAll("[data-group-id]").forEach(button=>button.addEventListener("click",()=>openTrip(button.dataset.groupId)))}
function openTrip(groupId){state.activeGroupId=groupId;selectedDayDate=null;setSummaryExpanded(false);const group=currentGroup();if(!group.tripStartDate){group.tripStartDate=today();group.testOffset=0}group.expenses.forEach(expense=>{if(!expense.date)expense.date=group.tripStartDate});saveState();$("#groups-screen").hidden=true;$("#setup-screen").hidden=true;$("#group-screen").hidden=false;renderTrip();window.scrollTo({top:0,behavior:"smooth"})}
function setSummaryExpanded(expanded){$("#header-summary").classList.toggle("mobile-open",expanded);$("#summary-toggle").setAttribute("aria-expanded",String(expanded));$("#summary-toggle span").textContent=expanded?"⌃":"⌄"}

function simulatedToday(group){return group.tripEndDate||addDays(today(),group.testOffset||0)}
function renderTrip(){const group=currentGroup();$("#dashboard-group-name").textContent=group.name;$("#member-line").innerHTML=group.members.map(member=>`<span title="${escapeHtml(member.name)}"><b>${memberInitials(member.name)}</b></span>`).join("");const current=simulatedToday(group);const days=dayDistance(group.tripStartDate,current)+1;$("#trip-day-label").textContent=group.tripEndDate?`ENDED ${formatDate(group.tripEndDate,{month:"short",day:"numeric"}).toUpperCase()}`:`DAY ${days} · STARTED ${formatDate(group.tripStartDate,{month:"short",day:"numeric"}).toUpperCase()}`;$("#end-trip").hidden=!!group.tripEndDate;$("#add-test-day").hidden=!!group.tripEndDate;renderExpenseFormMembers();renderTimeline();renderBalances()}
function memberInitials(name){const parts=name.trim().split(/\s+/);const initials=parts.length===1?parts[0].slice(0,2).toUpperCase():parts.slice(0,2).map(part=>part.charAt(0).toUpperCase()).join("");return escapeHtml(initials)}
function renderTimeline(){const group=currentGroup(),current=simulatedToday(group),count=dayDistance(group.tripStartDate,current)+1;carouselDates=Array.from({length:count},(_,index)=>addDays(group.tripStartDate,index));if(!selectedDayDate||!carouselDates.includes(selectedDayDate))selectedDayDate=current;const posted=group.expenses.filter(expense=>!expense.isDraft),total=posted.reduce((sum,expense)=>sum+expense.amount,0);$("#total-spend").textContent=money(total);$("#expense-count").textContent=posted.length?`${posted.length} ${posted.length===1?"expense":"expenses"}`:"No expenses yet";$("#timeline-list").innerHTML=carouselDates.map(date=>renderDayPanel(date,current)).join("");$("#timeline-list").querySelectorAll("[data-expense-date]").forEach(button=>button.addEventListener("click",()=>openExpenseForm(button.dataset.expenseDate,button.dataset.expensePeriod)));$("#timeline-list").querySelectorAll("[data-edit]").forEach(card=>{const edit=()=>{const expense=group.expenses.find(item=>item.id===card.dataset.edit);if(expense)openExpenseForm(expense.date,expenseTimePeriod(expense),expense)};card.addEventListener("click",edit);card.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();edit()}})});$("#timeline-list").querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();openDeleteModal(button.dataset.delete)}));updateCarousel()}
function updateCarousel(){const index=Math.max(0,carouselDates.indexOf(selectedDayDate)),track=$("#timeline-list"),panels=[...track.querySelectorAll(".day-panel")],panel=panels[index],viewport=$(".day-viewport");panels.forEach((item,itemIndex)=>item.classList.toggle("active",itemIndex===index));if(panel){const centeredOffset=panel.offsetLeft-(viewport.clientWidth-panel.offsetWidth)/2;track.style.transform=`translateX(-${Math.max(0,centeredOffset)}px)`}$("#previous-day").disabled=index===0;$("#next-day").disabled=index===carouselDates.length-1;$("#day-position").textContent=`Day ${index+1} of ${carouselDates.length}`;$("#day-dots").innerHTML=carouselDates.map((_,dotIndex)=>`<span class="${dotIndex===index?"active":""}"></span>`).join("")}
function moveCarousel(amount){const index=carouselDates.indexOf(selectedDayDate),next=Math.max(0,Math.min(carouselDates.length-1,index+amount));selectedDayDate=carouselDates[next];updateCarousel()}
function renderDayPanel(date,current){const group=currentGroup(),expenses=group.expenses.filter(expense=>expense.date===date),total=expenses.filter(expense=>!expense.isDraft).reduce((sum,expense)=>sum+expense.amount,0),dayNumber=dayDistance(group.tripStartDate,date)+1,isToday=date===current;const periods=[{id:"morning",label:"Morning",icon:"☀"},{id:"afternoon",label:"Afternoon",icon:"◐"},{id:"evening",label:"Evening",icon:"☾"}];return `<article class="day-panel"><div class="day-header"><div class="date-box"><strong>${fromDateKey(date).getDate()}</strong><span>${formatDate(date,{month:"short"})}</span></div><div><small>DAY ${dayNumber}${isToday?" · TODAY":""}</small><h3>${formatDate(date)}</h3></div><div class="day-total"><small>DAY TOTAL</small><strong>${money(total)}</strong></div></div><div class="day-periods">${periods.map(period=>renderPeriod(date,period,expenses)).join("")}</div></article>`}
function renderPeriod(date,period,expenses){const matching=expenses.filter(expense=>expenseTimePeriod(expense)===period.id),posted=matching.filter(expense=>!expense.isDraft),total=posted.reduce((sum,expense)=>sum+expense.amount,0),items=matching.map(renderExpenseItem).join("");return `<section class="day-period"><div class="period-marker"><span class="period-icon" role="img" aria-label="${period.label}">${period.icon}</span>${posted.length?`<small>${money(total)}</small>`:""}</div><div class="period-expenses">${items}</div><button class="period-add-button" type="button" data-expense-date="${date}" data-expense-period="${period.id}" aria-label="Add ${period.label.toLowerCase()} expense">+</button></section>`}
function expenseTimePeriod(expense){if(expense.period)return expense.period;const hour=expense.createdAt?new Date(expense.createdAt).getHours():9;return hour<12?"morning":hour<18?"afternoon":"evening"}
function renderExpenseItem(expense){const group=currentGroup();const payer=group.members.find(member=>member.id===expense.payerId);const names=expense.participantIds.map(id=>group.members.find(member=>member.id===id)?.name).filter(Boolean);const method=expense.splitMode==="unequal"?"custom":expense.splitMode==="percentage"?"percentage":"equal";return `<div class="expense-item${expense.isDraft?" draft":""}" data-edit="${expense.id}" role="button" tabindex="0" aria-label="Edit ${escapeHtml(expense.description)}"><div class="expense-icon">${escapeHtml(expense.description.charAt(0).toUpperCase())}</div><div class="expense-copy"><h3>${escapeHtml(expense.description)}${expense.isDraft?'<span class="draft-label">Draft</span>':""}</h3><p><span class="paid-by-copy">${escapeHtml(payer?.name||"Member")} paid</span><span class="split-copy"> · ${method} split with ${names.length===group.members.length?"everyone":names.map(escapeHtml).join(", ")}</span></p></div><strong>${money(expense.amount)}</strong><div class="expense-actions"><button class="delete-button" type="button" data-delete="${expense.id}" aria-label="Delete expense">×</button></div></div>`}

function renderExpenseFormMembers(){const members=currentGroup().members;$("#payer-list").innerHTML=members.map(member=>`<button type="button" data-payer-id="${member.id}" role="radio" aria-checked="false" aria-label="${escapeHtml(member.name)}" title="${escapeHtml(member.name)}">${memberInitials(member.name)}</button>`).join("");$("#payer-list").querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>setPayer(button.dataset.payerId)));setPayer(members[0].id);$("#split-list").innerHTML=members.map(member=>`<div class="split-person active" data-split-member="${member.id}"><button class="split-person-toggle" type="button" aria-pressed="true" aria-label="Include ${escapeHtml(member.name)} in the split"><span class="split-check" aria-hidden="true">✓</span><span class="mini-avatar" aria-hidden="true">${memberInitials(member.name)}</span><strong>${escapeHtml(member.name)}</strong></button><div class="allocation-input"><span>₱</span><input type="text" inputmode="decimal" data-share-member="${member.id}" value="0.00" aria-label="${escapeHtml(member.name)} share" autocomplete="off"></div></div>`).join("");$("#split-list").querySelectorAll(".split-person-toggle").forEach(button=>button.addEventListener("click",()=>toggleSplitPerson(button)));$("#split-list").querySelectorAll("[data-share-member]").forEach(input=>{attachMoneyInput(input);input.addEventListener("input",()=>{splitSharesCustomized=true;manualShareIds.add(input.dataset.shareMember);hideError("#expense-error");redistributeRemainingShares(input)})});manualShareIds.clear();splitSharesCustomized=false;redistributeEqualShares()}
function setPayer(memberId){$("#expense-payer").value=memberId;$("#payer-list").querySelectorAll("button").forEach(button=>{const selected=button.dataset.payerId===memberId;button.classList.toggle("active",selected);button.setAttribute("aria-checked",String(selected))})}
function selectedSplitRows(){return [...$("#split-list").querySelectorAll(".split-person.active")]}
function toggleSplitPerson(button){const row=button.closest(".split-person"),isActive=row.classList.contains("active");if(isActive&&selectedSplitRows().length===1)return showError("#expense-error","At least one person must be included.");row.classList.toggle("active",!isActive);button.setAttribute("aria-pressed",String(!isActive));const input=row.querySelector("[data-share-member]");input.disabled=isActive;hideError("#expense-error");redistributeEqualShares()}
function redistributeEqualShares(){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0,base=rows.length?Math.floor(amount/rows.length):0,remainder=rows.length?amount-base*rows.length:0;$("#split-list").querySelectorAll(".split-person").forEach(row=>{const input=row.querySelector("[data-share-member]"),index=rows.indexOf(row);input.value=formatCentsForInput(index<0?0:base+(index<remainder?1:0));input.disabled=index<0});manualShareIds.clear();splitSharesCustomized=false;updateSplitPreview()}
function redistributeRemainingShares(editedInput=null){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0;if(editedInput&&rows.length>1&&!rows.some(row=>!manualShareIds.has(row.dataset.splitMember))){const fallback=[...manualShareIds].find(id=>id!==editedInput.dataset.shareMember&&rows.some(row=>row.dataset.splitMember===id));if(fallback)manualShareIds.delete(fallback)}const automaticRows=rows.filter(row=>!manualShareIds.has(row.dataset.splitMember)),fixedTotal=rows.filter(row=>manualShareIds.has(row.dataset.splitMember)).reduce((total,row)=>{const cents=parseMoneyToCents(row.querySelector("[data-share-member]").value);return total+(Number.isFinite(cents)?cents:0)},0),remaining=Math.max(0,amount-fixedTotal),base=automaticRows.length?Math.floor(remaining/automaticRows.length):0,remainder=automaticRows.length?remaining-base*automaticRows.length:0;automaticRows.forEach((row,index)=>{row.querySelector("[data-share-member]").value=formatCentsForInput(base+(index<remainder?1:0))});updateSplitPreview()}
function handleExpenseAmountChange(){hideError("#expense-error");if(splitSharesCustomized)redistributeRemainingShares();else redistributeEqualShares()}
function openExpenseForm(date,period="morning",expense=null){expenseDate=date;expensePeriodName=period;editingExpenseId=expense?.id||null;$("#expense-date-label").textContent=`${formatDate(date)} · ${period}`.toUpperCase();$("#expense-title").textContent=expense?.isDraft?"Edit draft":expense?"Edit expense":"Add an expense";$("#save-draft-button").textContent=expense?.isDraft?"Update draft":"Save draft";$("#save-expense-button").innerHTML=`${expense&&!expense.isDraft?"Update":"Save"} expense <span>→</span>`;$("#expense-modal").hidden=false;document.body.classList.add("modal-open");if(expense)fillExpenseForm(expense);$("#expense-description").focus()}
function closeExpenseForm(){$("#expense-form").reset();editingExpenseId=null;manualShareIds.clear();splitSharesCustomized=false;$("#expense-title").textContent="Add an expense";$("#save-draft-button").textContent="Save draft";$("#save-expense-button").innerHTML="Save expense <span>→</span>";if(currentGroup())renderExpenseFormMembers();$("#expense-modal").hidden=true;document.body.classList.remove("modal-open");hideError("#expense-error")}
function openDeleteModal(expenseId){const expense=currentGroup().expenses.find(item=>item.id===expenseId);if(!expense)return;pendingEndTrip=false;pendingDeleteExpenseId=expenseId;$("#delete-title").textContent=`Delete “${expense.description}”?`;$("#delete-message").textContent="This expense will be permanently removed and everyone’s balance will be recalculated.";$("#confirm-delete").textContent="Delete";$("#delete-modal").hidden=false;document.body.classList.add("modal-open");$("#cancel-delete").focus()}
function openEndTripModal(){pendingDeleteExpenseId=null;pendingEndTrip=true;$("#delete-title").textContent="End this trip?";$("#delete-message").textContent="Today becomes the final trip day. You can still reopen the group and review its expenses.";$("#confirm-delete").textContent="End trip";$("#delete-modal").hidden=false;document.body.classList.add("modal-open");$("#cancel-delete").focus()}
function closeDeleteModal(){pendingDeleteExpenseId=null;pendingEndTrip=false;$("#delete-modal").hidden=true;document.body.classList.remove("modal-open")}
function confirmDelete(){if(pendingEndTrip){const group=currentGroup();group.tripEndDate=simulatedToday(group);saveState();closeDeleteModal();showGroups();return}if(!pendingDeleteExpenseId)return;const group=currentGroup();group.expenses=group.expenses.filter(expense=>expense.id!==pendingDeleteExpenseId);saveState();closeDeleteModal();renderTimeline();renderBalances()}
function fillExpenseForm(expense){$("#expense-description").value=expense.description;$("#expense-amount").value=formatCentsForInput(expense.amount);setPayer(expense.payerId);const included=new Set(expense.participantIds?.length?expense.participantIds:expense.shares.map(share=>share.id));$("#split-list").querySelectorAll(".split-person").forEach(row=>{const active=included.has(row.dataset.splitMember),button=row.querySelector(".split-person-toggle"),input=row.querySelector("[data-share-member]"),share=expense.shares.find(item=>item.id===input.dataset.shareMember);row.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));input.disabled=!active;input.value=formatCentsForInput(share?.amount||0)});manualShareIds.clear();const activeRows=selectedSplitRows();if(expense.splitMode!=="equal")activeRows.slice(0,-1).forEach(row=>manualShareIds.add(row.dataset.splitMember));splitSharesCustomized=expense.splitMode!=="equal";updateSplitPreview()}
function updateSplitPreview(){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0,sum=rows.reduce((total,row)=>{const cents=parseMoneyToCents(row.querySelector("[data-share-member]").value);return total+(Number.isFinite(cents)?cents:0)},0),difference=amount-sum,preview=$("#split-preview");preview.classList.toggle("valid",amount>0&&difference===0);preview.classList.toggle("invalid",amount>0&&difference!==0);preview.textContent=!rows.length?"Choose someone":!amount?`${rows.length} selected`:difference===0?"Balanced":difference<0?"Shares exceed total":"Shares do not match total"}
function buildShares(amount){const shares=selectedSplitRows().map(row=>{const input=row.querySelector("[data-share-member]");return{id:input.dataset.shareMember,amount:parseMoneyToCents(input.value)}});if(!shares.length)return{error:"Choose at least one person."};if(shares.some(share=>!Number.isFinite(share.amount)||share.amount<0))return{error:"Enter a valid share for each selected person."};const total=shares.reduce((sum,share)=>sum+share.amount,0);if(total!==amount)return{error:`Shares must add up to ${money(amount)}. ${money(total)} is currently allocated.`};const base=Math.floor(amount/shares.length),remainder=amount-base*shares.length,isEqual=shares.every((share,index)=>share.amount===base+(index<remainder?1:0));return{shares,mode:isEqual?"equal":"unequal"}}
function buildDraftShares(amount){const shares=selectedSplitRows().map(row=>{const input=row.querySelector("[data-share-member]"),parsed=parseMoneyToCents(input.value);return{id:input.dataset.shareMember,amount:Number.isFinite(parsed)&&parsed>=0?parsed:0}}),total=shares.reduce((sum,share)=>sum+share.amount,0),base=shares.length?Math.floor(amount/shares.length):0,remainder=shares.length?amount-base*shares.length:0,isEqual=total===amount&&shares.every((share,index)=>share.amount===base+(index<remainder?1:0));return{shares,mode:isEqual?"equal":"unequal"}}
function saveExpense(event,isDraft=false){event.preventDefault();const group=currentGroup(),rawDescription=$("#expense-description").value.trim(),parsedAmount=parseMoneyToCents($("#expense-amount").value),description=isDraft?(rawDescription||"Untitled expense"):rawDescription,amount=isDraft?(Number.isFinite(parsedAmount)&&parsedAmount>=0?parsedAmount:0):parsedAmount;if(!isDraft&&!description)return showError("#expense-error","Add a description.");if(!isDraft&&(!Number.isFinite(amount)||amount<1))return showError("#expense-error","Enter a valid amount greater than zero.");if(expenseDate>simulatedToday(group))return showError("#expense-error","Future expenses are not allowed.");const result=isDraft?buildDraftShares(amount):buildShares(amount);if(result.error)return showError("#expense-error",result.error);const participantIds=result.shares.map(share=>share.id),existing=group.expenses.find(expense=>expense.id===editingExpenseId);const record={id:existing?.id||makeId(),date:expenseDate,period:expensePeriodName,description,amount,payerId:$("#expense-payer").value,participantIds,shares:result.shares,splitMode:result.mode,splitDetails:null,isDraft,createdAt:existing?.createdAt||new Date()};if(existing)group.expenses=group.expenses.map(expense=>expense.id===existing.id?record:expense);else group.expenses.unshift(record);saveState();closeExpenseForm();renderTimeline();renderBalances()}
function addExpense(event){saveExpense(event,false)}
function saveDraft(event){saveExpense(event,true)}

function getBalances(){const group=currentGroup(),balances=new Map(group.members.map(member=>[member.id,0]));group.expenses.filter(expense=>!expense.isDraft).forEach(expense=>{balances.set(expense.payerId,balances.get(expense.payerId)+expense.amount);expense.shares.forEach(share=>balances.set(share.id,balances.get(share.id)-share.amount))});return balances}
function renderBalances(){const group=currentGroup(),balances=getBalances();$("#balance-list").innerHTML=group.members.map(member=>{const balance=balances.get(member.id),label=balance>0?"gets back":balance<0?"owes":"settled",tone=balance>0?"positive":balance<0?"negative":"neutral";return `<div class="balance-item"><span class="avatar">${memberInitials(member.name)}</span><div><strong>${escapeHtml(member.name)}</strong><small>${label}</small></div><b class="${tone}">${balance===0?money(0):`${balance>0?"+":"−"}${money(Math.abs(balance))}`}</b></div>`}).join("");renderSettlements(balances)}
function renderSettlements(balances){const group=currentGroup(),creditors=group.members.map(member=>({...member,amount:balances.get(member.id)})).filter(person=>person.amount>0).sort((a,b)=>b.amount-a.amount),debtors=group.members.map(member=>({...member,amount:-balances.get(member.id)})).filter(person=>person.amount>0).sort((a,b)=>b.amount-a.amount),payments=[];let ci=0,di=0;while(ci<creditors.length&&di<debtors.length){const amount=Math.min(creditors[ci].amount,debtors[di].amount);if(amount)payments.push({from:debtors[di].name,to:creditors[ci].name,amount});creditors[ci].amount-=amount;debtors[di].amount-=amount;if(!creditors[ci].amount)ci++;if(!debtors[di].amount)di++}$("#settlement-list").innerHTML=payments.length?payments.map(payment=>`<div class="settlement"><div><strong>${escapeHtml(payment.from)}</strong><span>pays</span><strong>${escapeHtml(payment.to)}</strong></div><b>${money(payment.amount)}</b></div>`).join(""):`<div class="all-set"><span>✓</span><p>${group.expenses.some(expense=>!expense.isDraft)?"Everyone is settled up.":"Settlements will appear here."}</p></div>`}

$("#group-form").addEventListener("submit",createGroup);$("#group-name").addEventListener("input",()=>hideError("#group-error"));$("#new-group-button").addEventListener("click",showSetup);$("#cancel-group").addEventListener("click",showGroups);$("#back-to-groups").addEventListener("click",showGroups);$("#home-button").addEventListener("click",()=>state.groups.length?showGroups():showSetup());$("#add-test-day").addEventListener("click",()=>{const group=currentGroup();group.testOffset=(group.testOffset||0)+1;selectedDayDate=null;saveState();renderTrip()});$("#end-trip").addEventListener("click",openEndTripModal);$("#modal-backdrop").addEventListener("click",closeExpenseForm);$("#cancel-expense").addEventListener("click",closeExpenseForm);$("#expense-form").addEventListener("submit",addExpense);$("#save-draft-button").addEventListener("click",saveDraft);$("#expense-amount").addEventListener("input",handleExpenseAmountChange);$("#delete-backdrop").addEventListener("click",closeDeleteModal);$("#cancel-delete").addEventListener("click",closeDeleteModal);$("#confirm-delete").addEventListener("click",confirmDelete);document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!$("#delete-modal").hidden)closeDeleteModal();else if(!$("#expense-modal").hidden)closeExpenseForm()});
$("#previous-day").addEventListener("click",()=>moveCarousel(-1));$("#next-day").addEventListener("click",()=>moveCarousel(1));const viewport=$(".day-viewport");viewport.addEventListener("touchstart",event=>{swipeStartX=event.changedTouches[0].clientX},{passive:true});viewport.addEventListener("touchend",event=>{if(swipeStartX===null)return;const distance=event.changedTouches[0].clientX-swipeStartX;if(Math.abs(distance)>45)moveCarousel(distance<0?1:-1);swipeStartX=null},{passive:true});window.addEventListener("resize",()=>{if(!$("#group-screen").hidden)updateCarousel()});
attachMoneyInput($("#expense-amount"));
$("#summary-toggle").addEventListener("click",()=>setSummaryExpanded($("#summary-toggle").getAttribute("aria-expanded")!=="true"));

function initializeApp(){const saved=dataStore.load();state.groups=saved.groups||[];state.groups.forEach(group=>{group.expenses=group.expenses||[];group.testOffset=group.testOffset||0;group.expenses.forEach(expense=>{if(!expense.shares&&expense.participantIds?.length){const base=Math.floor(expense.amount/expense.participantIds.length),remainder=expense.amount-base*expense.participantIds.length;expense.shares=expense.participantIds.map((id,index)=>({id,amount:base+(index<remainder?1:0)}))}})});if(state.groups.length)showGroups();else{renderPeopleInputs();$("#setup-screen").hidden=false}}
initializeApp();
