const MIN_PEOPLE=2,MAX_PEOPLE=20,ACCOUNTANT_ID="auditor";
const state={groups:[],activeGroupId:null,activeMemberId:null};
let draftPeople=["",""];let draftMemberIds=[null,null];let editingGroupId=null;let activeTripView="expenses";let splitSharesCustomized=false;let manualShareIds=new Set();let expenseDate=null;let expensePeriodName="morning";let editingExpenseId=null;let pendingDeleteExpenseId=null;let selectedDayDate=null;let carouselDates=[];let swipeStartX=null;
const $=selector=>document.querySelector(selector);
const money=cents=>new Intl.NumberFormat("en-PH",{style:"currency",currency:"PHP"}).format(cents/100);
function parseMoneyToCents(value){const cleaned=String(value??"").replace(/[,₱\s]/g,"");if(!/^\d*(\.\d{0,2})?$/.test(cleaned)||cleaned==="")return NaN;return Math.round(Number(cleaned)*100)}
function formatMoneyText(value){const raw=String(value??"").replace(/,/g,"").replace(/[^\d.]/g,"");if(!raw)return"";const hasDecimal=raw.includes("."),parts=raw.split("."),integer=(parts.shift()||"0").replace(/^0+(?=\d)/,"")||"0",decimals=parts.join("").slice(0,2),formatted=integer.replace(/\B(?=(\d{3})+(?!\d))/g,",");return hasDecimal?`${formatted}.${decimals}`:formatted}
function formatCentsForInput(cents){return (cents/100).toLocaleString("en-US",{minimumFractionDigits:2,maximumFractionDigits:2})}
function attachMoneyInput(input){input.addEventListener("input",()=>{input.value=formatMoneyText(input.value)});input.addEventListener("blur",()=>{const cents=parseMoneyToCents(input.value);if(Number.isFinite(cents))input.value=formatCentsForInput(cents)})}
const makeId=()=>`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const today=()=>toDateKey(new Date());
function toDateKey(date){return `${date.getFullYear()}-${String(date.getMonth()+1).padStart(2,"0")}-${String(date.getDate()).padStart(2,"0")}`}
function fromDateKey(key){const [year,month,day]=key.split("-").map(Number);return new Date(year,month-1,day)}
function addDays(key,count){const date=fromDateKey(key);date.setDate(date.getDate()+count);return toDateKey(date)}
function dayDistance(from,to){return Math.round((fromDateKey(to)-fromDateKey(from))/86400000)}
function formatDate(key,options={weekday:"long",month:"short",day:"numeric"}){return new Intl.DateTimeFormat("en-PH",options).format(fromDateKey(key))}
function currentGroup(){return state.groups.find(group=>group.id===state.activeGroupId)}

const dataStore={key:"anti-buraot:v2",legacyKey:"anti-buraot:v1",load(){try{const current=JSON.parse(localStorage.getItem(this.key));if(current&&Array.isArray(current.groups))return current;const legacy=JSON.parse(localStorage.getItem(this.legacyKey));if(legacy&&legacy.groupName&&Array.isArray(legacy.members)){const start=today();return{groups:[{id:makeId(),name:legacy.groupName,members:legacy.members,expenses:(legacy.expenses||[]).map(expense=>({...expense,date:expense.date||start})),tripStartDate:start,testOffset:0}]}}}catch{}return{groups:[]}},save(){try{localStorage.setItem(this.key,JSON.stringify({groups:state.groups}));return true}catch{return false}}};
function saveState(){dataStore.save()}
function showError(selector,message){const element=$(selector);element.textContent=message;element.hidden=false}
function hideError(selector){$(selector).hidden=true}
function escapeHtml(value){const element=document.createElement("span");element.textContent=value;return element.innerHTML}

function renderPeopleInputs(){const list=$("#people-list");list.innerHTML="";draftPeople.forEach((name,index)=>{const row=document.createElement("div");row.className="member-row";row.innerHTML=`<span class="member-avatar" aria-hidden="true">👤</span><input class="input" aria-label="Member ${index+1} name" maxlength="40" autocomplete="off" placeholder="${index===0?"Your name":`Member ${index+1} name`}">${draftPeople.length>MIN_PEOPLE?`<button class="remove-member" type="button" aria-label="Remove member ${index+1}">×</button>`:"<span></span>"}`;const input=row.querySelector("input");input.value=name;input.addEventListener("input",event=>{draftPeople[index]=event.target.value;updatePeopleCount();hideError("#group-error")});const remove=row.querySelector(".remove-member");if(remove)remove.addEventListener("click",()=>{draftPeople.splice(index,1);draftMemberIds.splice(index,1);renderPeopleInputs()});list.appendChild(row)});if(draftPeople.length<MAX_PEOPLE){const add=document.createElement("button");add.className="add-member-button";add.type="button";add.textContent="+ Add another member";add.addEventListener("click",()=>{draftPeople.push("");draftMemberIds.push(null);renderPeopleInputs();const inputs=list.querySelectorAll("input");inputs[inputs.length-1].focus()});list.appendChild(add)}updatePeopleCount()}
function updatePeopleCount(){$("#completion").textContent=`${draftPeople.filter(name=>name.trim()).length} of ${draftPeople.length} named`}

function showSetup(groupId=null){const group=typeof groupId==="string"?state.groups.find(item=>item.id===groupId):null;editingGroupId=group?.id||null;$("#group-form").reset();draftPeople=group?group.members.map(member=>member.name):["",""];draftMemberIds=group?group.members.map(member=>member.id):[null,null];$("#group-name").value=group?.name||"";$(".form-intro .step").textContent=group?"EDIT GROUP":"NEW GROUP";$(".form-intro h1").textContent=group?"Edit group":"Create a group";$(".form-intro p").textContent=group?"Update the group name or its members.":"Add the people who will share expenses.";renderPeopleInputs();$("#cancel-group").hidden=!state.groups.length;$("#groups-screen").hidden=true;$("#group-screen").hidden=true;$("#setup-screen").hidden=false;$("#group-name").focus()}
function showGroups(){state.activeGroupId=null;state.activeMemberId=null;editingGroupId=null;renderGroups();$("#setup-screen").hidden=true;$("#group-screen").hidden=true;$("#groups-screen").hidden=false;window.scrollTo({top:0,behavior:"smooth"})}
function createGroup(event){event.preventDefault();const name=$("#group-name").value.trim(),names=draftPeople.map(person=>person.trim());if(!name)return showError("#group-error","Give your group a name first.");if(names.some(person=>!person))return showError("#group-error","Add a name for every member.");if(new Set(names.map(person=>person.toLowerCase())).size!==names.length)return showError("#group-error","Each member needs a unique name.");const existing=state.groups.find(group=>group.id===editingGroupId),members=names.map((member,index)=>({id:draftMemberIds[index]||makeId(),name:member}));if(existing){const retainedIds=new Set(members.map(member=>member.id)),removedIds=existing.members.filter(member=>!retainedIds.has(member.id)).map(member=>member.id),history=[...existing.expenses,...(existing.deletedExpenses||[])],usedRemovedMember=history.some(expense=>removedIds.includes(expense.payerId)||expense.shares?.some(share=>removedIds.includes(share.id)));if(usedRemovedMember)return showError("#group-error","A member with recorded expenses cannot be removed.");existing.name=name;existing.members=members}else state.groups.unshift({id:makeId(),name,members,expenses:[],deletedExpenses:[],tripStartDate:null,testOffset:0});editingGroupId=null;saveState();showGroups()}
function renderGroups(){const list=$("#groups-list");list.innerHTML=state.groups.map(group=>{const posted=group.expenses.filter(expense=>!expense.isDraft),draftCount=group.expenses.length-posted.length,total=posted.reduce((sum,expense)=>sum+expense.amount,0);const status=group.tripEndDate?`Ended ${formatDate(group.tripEndDate,{month:"short",day:"numeric",year:"numeric"})}`:group.tripStartDate?`Started ${formatDate(group.tripStartDate,{month:"short",day:"numeric",year:"numeric"})}`:"Not started";return `<article class="group-card"><div class="group-card-icon">${escapeHtml(group.name.charAt(0).toUpperCase())}</div><div class="group-card-copy"><div class="group-name-row"><h2>${escapeHtml(group.name)}</h2><button class="edit-group-button" type="button" data-edit-group="${group.id}" aria-label="Edit ${escapeHtml(group.name)}" title="Edit group">✎</button></div><p>${group.members.length} members · ${status}</p>${group.expenses.length?`<small>${posted.length} ${posted.length===1?"expense":"expenses"} · ${money(total)}${draftCount?` · ${draftCount} ${draftCount===1?"draft":"drafts"}`:""}</small>`:""}</div><div class="open-trip-as"><small>${group.tripEndDate?"View trip as":"Open trip as"}</small><div>${group.members.map(member=>`<button type="button" data-group-id="${group.id}" data-member-id="${member.id}" aria-label="Open ${escapeHtml(group.name)} as ${escapeHtml(member.name)}" title="${escapeHtml(member.name)}">${memberInitials(member.name)}</button>`).join("")}<button class="accountant-option" type="button" data-group-id="${group.id}" data-member-id="${ACCOUNTANT_ID}" aria-label="Open ${escapeHtml(group.name)} as Auditor">AUDITOR</button></div></div></article>`}).join("");list.querySelectorAll("[data-group-id][data-member-id]").forEach(button=>button.addEventListener("click",()=>openTrip(button.dataset.groupId,button.dataset.memberId)));list.querySelectorAll("[data-edit-group]").forEach(button=>button.addEventListener("click",()=>showSetup(button.dataset.editGroup)))}
function openTrip(groupId,memberId){state.activeGroupId=groupId;state.activeMemberId=memberId;selectedDayDate=null;activeTripView="expenses";const group=currentGroup();if(!group.tripStartDate){group.tripStartDate=today();group.testOffset=0}group.expenses.forEach(expense=>{if(!expense.date)expense.date=group.tripStartDate});saveState();$("#groups-screen").hidden=true;$("#setup-screen").hidden=true;$("#group-screen").hidden=false;renderTrip();setTripView("expenses");window.scrollTo({top:0,behavior:"smooth"})}
function setTripView(view){activeTripView=view;const showSummary=view==="summary";$("#summary-view").hidden=!showSummary;$("#summary-view").classList.toggle("mobile-open",showSummary);$("#expenses-view").hidden=showSummary;$("#expenses-footer").hidden=showSummary;document.querySelectorAll("[data-trip-view]").forEach(button=>{const active=button.dataset.tripView===view;button.classList.toggle("active",active);button.setAttribute("aria-selected",String(active))});window.scrollTo({top:0,behavior:"smooth"})}

function simulatedToday(group){return group.tripEndDate||addDays(today(),group.testOffset||0)}
function renderTrip(){const group=currentGroup(),current=simulatedToday(group),days=dayDistance(group.tripStartDate,current)+1,status=group.tripEndDate?`Ended ${formatDate(group.tripEndDate,{month:"short",day:"numeric"})}`:`Day ${days}, Started ${formatDate(group.tripStartDate,{month:"short",day:"numeric"})}`,isAuditor=state.activeMemberId===ACCOUNTANT_ID;$("#trip-day-label").innerHTML=`<strong>${escapeHtml(group.name)}</strong><span>${status}</span>`;$("#summary-view").classList.toggle("auditor-summary",isAuditor);$("#spending-summary-label").textContent=isAuditor?"Spending overview":"Your spending";$("#add-test-day").hidden=!!group.tripEndDate;renderExpenseFormMembers();renderTimeline();renderBalances()}
function memberInitials(name){const parts=name.trim().split(/\s+/);const initials=parts.length===1?parts[0].slice(0,2).toUpperCase():parts.slice(0,2).map(part=>part.charAt(0).toUpperCase()).join("");return escapeHtml(initials)}
function renderTimeline(){const group=currentGroup(),current=simulatedToday(group),count=dayDistance(group.tripStartDate,current)+1;carouselDates=Array.from({length:count},(_,index)=>addDays(group.tripStartDate,index));if(!selectedDayDate||!carouselDates.includes(selectedDayDate))selectedDayDate=current;const posted=group.expenses.filter(expense=>!expense.isDraft),total=posted.reduce((sum,expense)=>sum+expense.amount,0);$("#total-spend").textContent=money(total);$("#expense-count").textContent=posted.length?`${posted.length} ${posted.length===1?"expense":"expenses"}`:"No expenses yet";$("#timeline-list").innerHTML=carouselDates.map(date=>renderDayPanel(date,current)).join("");$("#timeline-list").querySelectorAll("[data-expense-date]").forEach(button=>button.addEventListener("click",()=>openExpenseForm(button.dataset.expenseDate,button.dataset.expensePeriod)));$("#timeline-list").querySelectorAll("[data-edit]").forEach(card=>{const edit=()=>{const expense=group.expenses.find(item=>item.id===card.dataset.edit);if(expense)openExpenseForm(expense.date,expenseTimePeriod(expense),expense)};card.addEventListener("click",edit);card.addEventListener("keydown",event=>{if(event.key==="Enter"||event.key===" "){event.preventDefault();edit()}})});$("#timeline-list").querySelectorAll("[data-delete]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();openDeleteModal(button.dataset.delete)}));$("#timeline-list").querySelectorAll("[data-duplicate-summary]").forEach(button=>button.addEventListener("click",event=>{event.stopPropagation();openDuplicateSummary(button.dataset.duplicateSummary)}));updateCarousel()}
function updateCarousel(){const index=Math.max(0,carouselDates.indexOf(selectedDayDate)),track=$("#timeline-list"),panels=[...track.querySelectorAll(".day-panel")],panel=panels[index],viewport=$(".day-viewport");panels.forEach((item,itemIndex)=>item.classList.toggle("active",itemIndex===index));if(panel){const centeredOffset=panel.offsetLeft-(viewport.clientWidth-panel.offsetWidth)/2,viewportStyle=getComputedStyle(viewport),verticalPadding=parseFloat(viewportStyle.paddingTop)+parseFloat(viewportStyle.paddingBottom);track.style.transform=`translateX(-${Math.max(0,centeredOffset)}px)`;viewport.style.height=`${panel.offsetHeight+verticalPadding}px`}$("#previous-day").disabled=index===0;$("#next-day").disabled=index===carouselDates.length-1;$("#day-position").textContent=`Day ${index+1} of ${carouselDates.length}`;$("#day-dots").innerHTML=carouselDates.map((_,dotIndex)=>`<span class="${dotIndex===index?"active":""}"></span>`).join("")}
function moveCarousel(amount){const index=carouselDates.indexOf(selectedDayDate),next=Math.max(0,Math.min(carouselDates.length-1,index+amount));if(next===index)return;selectedDayDate=carouselDates[next];updateCarousel();if(window.matchMedia("(max-width: 540px)").matches){const panel=$("#timeline-list .day-panel.active");if(panel){const top=panel.getBoundingClientRect().top+window.scrollY-8;window.scrollTo({top,behavior:"smooth"})}}}
function renderDayPanel(date,current){const group=currentGroup(),active=group.expenses.filter(expense=>expense.date===date),deleted=state.activeMemberId===ACCOUNTANT_ID?(group.deletedExpenses||[]).filter(expense=>expense.date===date):[],expenses=[...active,...deleted],total=active.filter(expense=>!expense.isDraft).reduce((sum,expense)=>sum+expense.amount,0),dayNumber=dayDistance(group.tripStartDate,date)+1,isToday=date===current;const periods=[{id:"morning",label:"Morning",icon:"☀"},{id:"afternoon",label:"Afternoon",icon:"◐"},{id:"evening",label:"Evening",icon:"☾"}];return `<article class="day-panel"><div class="day-header"><div class="date-box"><strong>${fromDateKey(date).getDate()}</strong><span>${formatDate(date,{month:"short"})}</span></div><div><small>DAY ${dayNumber}${isToday?" · TODAY":""}</small><h3>${formatDate(date)}</h3></div><div class="day-total"><small>DAY TOTAL</small><strong>${money(total)}</strong></div></div><div class="day-periods">${periods.map(period=>renderPeriod(date,period,expenses)).join("")}</div></article>`}
function renderPeriod(date,period,expenses){const matching=expenses.filter(expense=>expenseTimePeriod(expense)===period.id),active=matching.filter(expense=>!expense.isDeleted),posted=active.filter(expense=>!expense.isDraft),total=posted.reduce((sum,expense)=>sum+expense.amount,0),items=matching.map(renderExpenseItem).join(""),isAuditEmpty=state.activeMemberId===ACCOUNTANT_ID&&!active.length;return `<section class="day-period${isAuditEmpty?" accountant-empty-period":""}"><div class="period-marker"><span class="period-icon" role="img" aria-label="${period.label}">${period.icon}</span>${posted.length?`<small>${money(total)}</small>`:""}${isAuditEmpty?'<small class="audit-note"><b>!</b> No entries</small>':""}</div><div class="period-expenses">${items}</div><button class="period-add-button" type="button" data-expense-date="${date}" data-expense-period="${period.id}" aria-label="Add ${period.label.toLowerCase()} expense">+</button></section>`}
function expenseTimePeriod(expense){if(expense.period)return expense.period;const hour=expense.createdAt?new Date(expense.createdAt).getHours():9;return hour<12?"morning":hour<18?"afternoon":"evening"}
function duplicateSignature(expense){const shares=[...(expense.shares||[])].sort((a,b)=>a.id.localeCompare(b.id)).map(share=>`${share.id}:${share.amount}`).join("|");return `${expense.amount}|${shares}`}
function potentialDuplicates(expense){if(expense.isDeleted)return[];const signature=duplicateSignature(expense);return currentGroup().expenses.filter(item=>!item.isDeleted&&item.id!==expense.id&&duplicateSignature(item)===signature)}
function isPotentialDuplicate(expense){return potentialDuplicates(expense).length>0}
function renderExpenseItem(expense){const group=currentGroup(),payer=group.members.find(member=>member.id===expense.payerId),viewerId=state.activeMemberId,isAccountant=viewerId===ACCOUNTANT_ID,isDuplicate=isAccountant&&isPotentialDuplicate(expense),viewerShare=expense.shares.find(share=>share.id===viewerId)?.amount||0,viewerNet=isAccountant?expense.amount:expense.payerId===viewerId?expense.amount-viewerShare:-viewerShare,viewerLabel=isAccountant?"total":viewerNet>0?"lent":viewerNet<0?"owes":"settled",viewerTone=isAccountant?"settled":viewerNet>0?"lent":viewerNet<0?"owes":"settled",viewerValue=money(Math.abs(viewerNet)),viewerAmount=`<div class="viewer-expense-amount ${viewerTone}">${expense.isDraft?"":`<small>${viewerLabel}</small>`}<strong>${viewerValue}</strong></div>`,shareDetails=expense.shares.map(share=>{const member=group.members.find(item=>item.id===share.id);return member?`<span>${escapeHtml(member.name)}: <b>${money(share.amount)}</b></span>`:""}).join(""),statusBadges=`${expense.isDraft?'<span class="draft-label">Draft</span>':""}${expense.isDeleted?'<span class="audit-label deleted-label">Deleted</span>':""}${isDuplicate?`<button class="audit-label duplicate-label" type="button" data-duplicate-summary="${expense.id}">Possible duplicate</button>`:""}`,editAttrs=expense.isDeleted?"":` data-edit="${expense.id}" role="button" tabindex="0" aria-label="Edit ${escapeHtml(expense.description)}"`,deleteAction=expense.isDeleted?"":`<div class="expense-actions"><button class="delete-button" type="button" data-delete="${expense.id}" aria-label="Delete expense">×</button></div>`;return `<div class="expense-item${expense.isDraft?" draft":""}${expense.isDeleted?" deleted-entry":""}${isDuplicate?" potential-duplicate":""}"${editAttrs}><div class="expense-icon">${escapeHtml(expense.description.charAt(0).toUpperCase())}</div><div class="expense-copy"><h3>${escapeHtml(expense.description)}${statusBadges}</h3><p class="desktop-split-details"><span>${escapeHtml(payer?.name||"Member")} paid <b>${money(expense.amount)}</b>.</span>${shareDetails}</p><p class="mobile-expense-details">${escapeHtml(payer?.name||"Member")} paid <b>${money(expense.amount)}</b>.</p></div>${viewerAmount}${deleteAction}</div>`}

function renderExpenseFormMembers(){const members=currentGroup().members;$("#payer-list").innerHTML=members.map(member=>`<button type="button" data-payer-id="${member.id}" role="radio" aria-checked="false" aria-label="${escapeHtml(member.name)}" title="${escapeHtml(member.name)}">${memberInitials(member.name)}</button>`).join("");$("#payer-list").querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>setPayer(button.dataset.payerId)));setPayer(members.some(member=>member.id===state.activeMemberId)?state.activeMemberId:members[0].id);$("#split-list").innerHTML=members.map(member=>`<div class="split-person active" data-split-member="${member.id}"><button class="split-person-toggle" type="button" aria-pressed="true" aria-label="Include ${escapeHtml(member.name)} in the split"><span class="split-check" aria-hidden="true">✓</span><span class="mini-avatar" aria-hidden="true">${memberInitials(member.name)}</span><strong>${escapeHtml(member.name)}</strong></button><div class="allocation-input"><span>₱</span><input type="text" inputmode="decimal" data-share-member="${member.id}" value="0.00" aria-label="${escapeHtml(member.name)} share" autocomplete="off"></div></div>`).join("");$("#split-list").querySelectorAll(".split-person-toggle").forEach(button=>button.addEventListener("click",()=>toggleSplitPerson(button)));$("#split-list").querySelectorAll("[data-share-member]").forEach(input=>{attachMoneyInput(input);input.addEventListener("input",()=>{splitSharesCustomized=true;manualShareIds.add(input.dataset.shareMember);hideError("#expense-error");redistributeRemainingShares(input)})});manualShareIds.clear();splitSharesCustomized=false;redistributeEqualShares()}
function setPayer(memberId){$("#expense-payer").value=memberId;$("#payer-list").querySelectorAll("button").forEach(button=>{const selected=button.dataset.payerId===memberId;button.classList.toggle("active",selected);button.setAttribute("aria-checked",String(selected))})}
function selectedSplitRows(){return [...$("#split-list").querySelectorAll(".split-person.active")]}
function toggleSplitPerson(button){const row=button.closest(".split-person"),isActive=row.classList.contains("active");if(isActive&&selectedSplitRows().length===1)return showError("#expense-error","At least one person must be included.");row.classList.toggle("active",!isActive);button.setAttribute("aria-pressed",String(!isActive));const input=row.querySelector("[data-share-member]");input.disabled=isActive;hideError("#expense-error");redistributeEqualShares()}
function redistributeEqualShares(){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0,base=rows.length?Math.floor(amount/rows.length):0,remainder=rows.length?amount-base*rows.length:0;$("#split-list").querySelectorAll(".split-person").forEach(row=>{const input=row.querySelector("[data-share-member]"),index=rows.indexOf(row);input.value=formatCentsForInput(index<0?0:base+(index<remainder?1:0));input.disabled=index<0});manualShareIds.clear();splitSharesCustomized=false;updateSplitPreview()}
function redistributeRemainingShares(editedInput=null){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0;if(editedInput&&rows.length>1&&!rows.some(row=>!manualShareIds.has(row.dataset.splitMember))){const fallback=[...manualShareIds].find(id=>id!==editedInput.dataset.shareMember&&rows.some(row=>row.dataset.splitMember===id));if(fallback)manualShareIds.delete(fallback)}const automaticRows=rows.filter(row=>!manualShareIds.has(row.dataset.splitMember)),fixedTotal=rows.filter(row=>manualShareIds.has(row.dataset.splitMember)).reduce((total,row)=>{const cents=parseMoneyToCents(row.querySelector("[data-share-member]").value);return total+(Number.isFinite(cents)?cents:0)},0),remaining=Math.max(0,amount-fixedTotal),base=automaticRows.length?Math.floor(remaining/automaticRows.length):0,remainder=automaticRows.length?remaining-base*automaticRows.length:0;automaticRows.forEach((row,index)=>{row.querySelector("[data-share-member]").value=formatCentsForInput(base+(index<remainder?1:0))});updateSplitPreview()}
function handleExpenseAmountChange(){hideError("#expense-error");if(splitSharesCustomized)redistributeRemainingShares();else redistributeEqualShares()}
function openExpenseForm(date,period="morning",expense=null){expenseDate=date;expensePeriodName=period;editingExpenseId=expense?.id||null;$("#expense-date-label").textContent=`${formatDate(date)} · ${period}`.toUpperCase();$("#expense-title").textContent=expense?.isDraft?"Edit draft":expense?"Edit expense":"Add an expense";$("#save-draft-button").textContent=expense?.isDraft?"Update draft":"Save draft";$("#save-expense-button").innerHTML=`${expense&&!expense.isDraft?"Update":"Save"} expense <span>→</span>`;$("#expense-modal").hidden=false;document.body.classList.add("modal-open");if(expense)fillExpenseForm(expense);if(window.matchMedia("(hover: hover) and (pointer: fine)").matches)$("#expense-description").focus()}
function closeExpenseForm(){$("#expense-form").reset();editingExpenseId=null;manualShareIds.clear();splitSharesCustomized=false;$("#expense-title").textContent="Add an expense";$("#save-draft-button").textContent="Save draft";$("#save-expense-button").innerHTML="Save expense <span>→</span>";if(currentGroup())renderExpenseFormMembers();$("#expense-modal").hidden=true;document.body.classList.remove("modal-open");hideError("#expense-error")}
function openDeleteModal(expenseId){const expense=currentGroup().expenses.find(item=>item.id===expenseId);if(!expense)return;pendingDeleteExpenseId=expenseId;$("#delete-title").textContent=`Delete “${expense.description}”?`;$("#delete-message").textContent="This expense will be removed from trip totals and retained in the Auditor view.";$("#confirm-delete").textContent="Delete";$("#delete-modal").hidden=false;document.body.classList.add("modal-open");$("#cancel-delete").focus()}
function closeDeleteModal(){pendingDeleteExpenseId=null;$("#delete-modal").hidden=true;document.body.classList.remove("modal-open")}
function confirmDelete(){if(!pendingDeleteExpenseId)return;const group=currentGroup(),deleted=group.expenses.find(expense=>expense.id===pendingDeleteExpenseId);if(deleted){group.deletedExpenses=group.deletedExpenses||[];group.deletedExpenses.unshift({...deleted,isDeleted:true,deletedAt:new Date()});group.expenses=group.expenses.filter(expense=>expense.id!==pendingDeleteExpenseId)}saveState();closeDeleteModal();renderTimeline();renderBalances()}
function fillExpenseForm(expense){$("#expense-description").value=expense.description;$("#expense-amount").value=formatCentsForInput(expense.amount);setPayer(expense.payerId);const included=new Set(expense.participantIds?.length?expense.participantIds:expense.shares.map(share=>share.id));$("#split-list").querySelectorAll(".split-person").forEach(row=>{const active=included.has(row.dataset.splitMember),button=row.querySelector(".split-person-toggle"),input=row.querySelector("[data-share-member]"),share=expense.shares.find(item=>item.id===input.dataset.shareMember);row.classList.toggle("active",active);button.setAttribute("aria-pressed",String(active));input.disabled=!active;input.value=formatCentsForInput(share?.amount||0)});manualShareIds.clear();const activeRows=selectedSplitRows();if(expense.splitMode!=="equal")activeRows.slice(0,-1).forEach(row=>manualShareIds.add(row.dataset.splitMember));splitSharesCustomized=expense.splitMode!=="equal";updateSplitPreview()}
function updateSplitPreview(){const rows=selectedSplitRows(),parsedAmount=parseMoneyToCents($("#expense-amount").value),amount=Number.isFinite(parsedAmount)?parsedAmount:0,sum=rows.reduce((total,row)=>{const cents=parseMoneyToCents(row.querySelector("[data-share-member]").value);return total+(Number.isFinite(cents)?cents:0)},0),difference=amount-sum,preview=$("#split-preview");preview.classList.toggle("valid",amount>0&&difference===0);preview.classList.toggle("invalid",amount>0&&difference!==0);preview.textContent=!rows.length?"Choose someone":!amount?`${rows.length} selected`:difference===0?"Balanced":difference<0?"Shares exceed total":"Shares do not match total"}
function buildShares(amount){const shares=selectedSplitRows().map(row=>{const input=row.querySelector("[data-share-member]");return{id:input.dataset.shareMember,amount:parseMoneyToCents(input.value)}});if(!shares.length)return{error:"Choose at least one person."};if(shares.some(share=>!Number.isFinite(share.amount)||share.amount<0))return{error:"Enter a valid share for each selected person."};const total=shares.reduce((sum,share)=>sum+share.amount,0);if(total!==amount)return{error:`Shares must add up to ${money(amount)}. ${money(total)} is currently allocated.`};const base=Math.floor(amount/shares.length),remainder=amount-base*shares.length,isEqual=shares.every((share,index)=>share.amount===base+(index<remainder?1:0));return{shares,mode:isEqual?"equal":"unequal"}}
function buildDraftShares(amount){const shares=selectedSplitRows().map(row=>{const input=row.querySelector("[data-share-member]"),parsed=parseMoneyToCents(input.value);return{id:input.dataset.shareMember,amount:Number.isFinite(parsed)&&parsed>=0?parsed:0}}),total=shares.reduce((sum,share)=>sum+share.amount,0),base=shares.length?Math.floor(amount/shares.length):0,remainder=shares.length?amount-base*shares.length:0,isEqual=total===amount&&shares.every((share,index)=>share.amount===base+(index<remainder?1:0));return{shares,mode:isEqual?"equal":"unequal"}}
function saveExpense(event,isDraft=false){event.preventDefault();const group=currentGroup(),rawDescription=$("#expense-description").value.trim(),parsedAmount=parseMoneyToCents($("#expense-amount").value),description=isDraft?(rawDescription||"Untitled expense"):rawDescription,amount=isDraft?(Number.isFinite(parsedAmount)&&parsedAmount>=0?parsedAmount:0):parsedAmount;if(!isDraft&&!description)return showError("#expense-error","Add a description.");if(!isDraft&&(!Number.isFinite(amount)||amount<1))return showError("#expense-error","Enter a valid amount greater than zero.");if(expenseDate>simulatedToday(group))return showError("#expense-error","Future expenses are not allowed.");const result=isDraft?buildDraftShares(amount):buildShares(amount);if(result.error)return showError("#expense-error",result.error);const participantIds=result.shares.map(share=>share.id),existing=group.expenses.find(expense=>expense.id===editingExpenseId);const record={id:existing?.id||makeId(),date:expenseDate,period:expensePeriodName,description,amount,payerId:$("#expense-payer").value,participantIds,shares:result.shares,splitMode:result.mode,splitDetails:null,isDraft,createdAt:existing?.createdAt||new Date()};if(existing)group.expenses=group.expenses.map(expense=>expense.id===existing.id?record:expense);else group.expenses.unshift(record);saveState();closeExpenseForm();renderTimeline();renderBalances()}
function addExpense(event){saveExpense(event,false)}
function saveDraft(event){saveExpense(event,true)}

function getBalances(){const group=currentGroup(),balances=new Map(group.members.map(member=>[member.id,0]));group.expenses.filter(expense=>!expense.isDraft).forEach(expense=>{balances.set(expense.payerId,balances.get(expense.payerId)+expense.amount);expense.shares.forEach(share=>balances.set(share.id,balances.get(share.id)-share.amount))});return balances}
function getViewerRelations(){const group=currentGroup(),viewerId=state.activeMemberId,relations=new Map(group.members.filter(member=>member.id!==viewerId).map(member=>[member.id,{lent:0,owes:0}]));group.expenses.filter(expense=>!expense.isDraft).forEach(expense=>{if(expense.payerId===viewerId){expense.shares.forEach(share=>{if(share.id!==viewerId&&relations.has(share.id))relations.get(share.id).lent+=share.amount})}else{const viewerShare=expense.shares.find(share=>share.id===viewerId)?.amount||0;if(viewerShare&&relations.has(expense.payerId))relations.get(expense.payerId).owes+=viewerShare}});return relations}
function getInterPersonRelations(){const relations=new Map();currentGroup().expenses.filter(expense=>!expense.isDraft).forEach(expense=>expense.shares.forEach(share=>{if(share.id===expense.payerId||!share.amount)return;const key=`${share.id}\u0000${expense.payerId}`;relations.set(key,(relations.get(key)||0)+share.amount)}));return [...relations].map(([key,amount])=>{const [debtorId,creditorId]=key.split("\u0000");return{debtorId,creditorId,amount}})}
function summarySection(label,items,emptyMessage){return `<section class="summary-balance-section"><small>${label}</small><div class="summary-balance-items">${items.length?items.join(""):`<span class="viewer-settled">${emptyMessage}</span>`}</div></section>`}
function relationSummaryItem(debtorId,creditorId,label,amount,tone){return `<button class="balance-item relation-summary-button" type="button" data-relation-debtor="${debtorId}" data-relation-creditor="${creditorId}"><span><strong>${label}</strong></span><b class="${tone}">${money(amount)}</b></button>`}
function renderComputationDetails(details){const groups=new Map();details.forEach(item=>{if(!groups.has(item.expense.date))groups.set(item.expense.date,[]);groups.get(item.expense.date).push(item)});return [...groups].map(([date,items])=>`<section class="relation-date-group"><h3>${formatDate(date,{weekday:"short",month:"short",day:"numeric",year:"numeric"})}</h3><div>${items.map(item=>`<div class="relation-detail-row"><strong>${escapeHtml(item.expense.description)}</strong><b>${money(item.amount)}</b></div>`).join("")}</div></section>`).join("")}
function renderDuplicateDetails(expenses){const group=currentGroup(),groups=new Map();expenses.forEach(expense=>{if(!groups.has(expense.date))groups.set(expense.date,[]);groups.get(expense.date).push(expense)});return [...groups].map(([date,items])=>`<section class="relation-date-group"><h3>${formatDate(date,{weekday:"short",month:"short",day:"numeric",year:"numeric"})}</h3><div>${items.map(expense=>{const payer=group.members.find(member=>member.id===expense.payerId),shares=expense.shares.map(share=>{const member=group.members.find(item=>item.id===share.id);return member?`${escapeHtml(member.name)} ${money(share.amount)}`:""}).filter(Boolean).join(" · ");return `<div class="relation-detail-row duplicate-detail-row"><span><strong>${escapeHtml(expense.description)}</strong><small>Paid by ${escapeHtml(payer?.name||"Member")} · ${shares}</small></span><b>${money(expense.amount)}</b></div>`}).join("")}</div></section>`).join("")}
function openDuplicateSummary(expenseId){const expense=currentGroup().expenses.find(item=>item.id===expenseId);if(!expense)return;const matches=[expense,...potentialDuplicates(expense)].sort((a,b)=>a.date.localeCompare(b.date)||new Date(a.createdAt)-new Date(b.createdAt));$("#relation-kicker").textContent="DUPLICATE AUDIT";$("#relation-title").textContent="Possible duplicate expenses";$("#relation-total").textContent=`${matches.length} matching entries`;$("#relation-details").innerHTML=renderDuplicateDetails(matches);$("#relation-modal").hidden=false;document.body.classList.add("modal-open");$("#close-relation").focus()}
function openRelationSummary(debtorId,creditorId){const group=currentGroup(),debtor=group.members.find(member=>member.id===debtorId),creditor=group.members.find(member=>member.id===creditorId);if(!debtor||!creditor)return;const details=group.expenses.filter(expense=>!expense.isDraft&&expense.payerId===creditorId).map(expense=>({expense,amount:expense.shares.find(share=>share.id===debtorId)?.amount||0})).filter(item=>item.amount>0).sort((a,b)=>a.expense.date.localeCompare(b.expense.date)||new Date(a.expense.createdAt)-new Date(b.expense.createdAt)),total=details.reduce((sum,item)=>sum+item.amount,0);$("#relation-kicker").textContent="INTER-PERSON COMPUTATION";$("#relation-title").textContent=`${debtor.name} owes ${creditor.name}`;$("#relation-total").textContent=money(total);$("#relation-details").innerHTML=renderComputationDetails(details);$("#relation-modal").hidden=false;document.body.classList.add("modal-open");$("#close-relation").focus()}
function openMemberShareSummary(memberId){const group=currentGroup(),member=group.members.find(item=>item.id===memberId);if(!member)return;const details=group.expenses.filter(expense=>!expense.isDraft).map(expense=>({expense,amount:expense.shares.find(share=>share.id===memberId)?.amount||0})).filter(item=>item.amount>0).sort((a,b)=>a.expense.date.localeCompare(b.expense.date)||new Date(a.expense.createdAt)-new Date(b.expense.createdAt)),total=details.reduce((sum,item)=>sum+item.amount,0);$("#relation-kicker").textContent="SHARE COMPUTATION";$("#relation-title").textContent=`${member.name}’s expense share`;$("#relation-total").textContent=money(total);$("#relation-details").innerHTML=renderComputationDetails(details);$("#relation-modal").hidden=false;document.body.classList.add("modal-open");$("#close-relation").focus()}
function closeRelationSummary(){$("#relation-modal").hidden=true;document.body.classList.remove("modal-open")}
function renderSpendingBreakdown(){const group=currentGroup(),posted=group.expenses.filter(expense=>!expense.isDraft),members=state.activeMemberId===ACCOUNTANT_ID?group.members:group.members.filter(member=>member.id===state.activeMemberId);$("#spending-breakdown").innerHTML=members.map(member=>{const paid=posted.filter(expense=>expense.payerId===member.id).reduce((sum,expense)=>sum+expense.amount,0),share=posted.reduce((sum,expense)=>sum+(expense.shares.find(item=>item.id===member.id)?.amount||0),0),label=state.activeMemberId===ACCOUNTANT_ID?member.name:"You";return `<span><b>${escapeHtml(label)}</b><em>Paid ${money(paid)}</em><button class="spending-share-button" type="button" data-share-summary="${member.id}">Share ${money(share)}</button></span>`}).join("");$("#spending-breakdown").querySelectorAll("[data-share-summary]").forEach(button=>button.addEventListener("click",()=>openMemberShareSummary(button.dataset.shareSummary)))}
function renderBalances(){const group=currentGroup(),balances=getBalances(),interItems=[],consolidatedItems=[];renderSpendingBreakdown();if(state.activeMemberId===ACCOUNTANT_ID){getInterPersonRelations().forEach(relation=>{const debtor=group.members.find(member=>member.id===relation.debtorId),creditor=group.members.find(member=>member.id===relation.creditorId);if(debtor&&creditor)interItems.push(relationSummaryItem(debtor.id,creditor.id,`${escapeHtml(debtor.name)} owes ${escapeHtml(creditor.name)}`,relation.amount,"negative"))});group.members.forEach(member=>{const balance=balances.get(member.id),label=balance>0?`${escapeHtml(member.name)} gets back`:balance<0?`${escapeHtml(member.name)} owes`:`${escapeHtml(member.name)} is settled`,tone=balance>0?"positive":balance<0?"negative":"neutral";consolidatedItems.push(`<div class="balance-item"><div><strong>${label}</strong></div><b class="${tone}">${money(Math.abs(balance))}</b></div>`)})}else{const relations=getViewerRelations();group.members.filter(member=>member.id!==state.activeMemberId).forEach(member=>{const relation=relations.get(member.id);if(relation?.lent)interItems.push(relationSummaryItem(member.id,state.activeMemberId,`${escapeHtml(member.name)} owes you`,relation.lent,"positive"));if(relation?.owes)interItems.push(relationSummaryItem(state.activeMemberId,member.id,`You owe ${escapeHtml(member.name)}`,relation.owes,"negative"))});const balance=balances.get(state.activeMemberId)||0,label=balance>0?"You get back":balance<0?"You owe":"You are settled",tone=balance>0?"positive":balance<0?"negative":"neutral";consolidatedItems.push(`<div class="balance-item"><div><strong>${label}</strong></div><b class="${tone}">${money(Math.abs(balance))}</b></div>`)}$("#balance-list").innerHTML=summarySection("Inter-person",interItems,"No direct balances")+summarySection("Consolidated",consolidatedItems,"No balance");$("#balance-list").querySelectorAll("[data-relation-debtor]").forEach(button=>button.addEventListener("click",()=>openRelationSummary(button.dataset.relationDebtor,button.dataset.relationCreditor)));renderSettlements(balances)}
function renderSettlements(balances){const group=currentGroup(),creditors=group.members.map(member=>({...member,amount:balances.get(member.id)})).filter(person=>person.amount>0).sort((a,b)=>b.amount-a.amount),debtors=group.members.map(member=>({...member,amount:-balances.get(member.id)})).filter(person=>person.amount>0).sort((a,b)=>b.amount-a.amount),payments=[];let ci=0,di=0;while(ci<creditors.length&&di<debtors.length){const amount=Math.min(creditors[ci].amount,debtors[di].amount);if(amount)payments.push({from:debtors[di].name,to:creditors[ci].name,amount});creditors[ci].amount-=amount;debtors[di].amount-=amount;if(!creditors[ci].amount)ci++;if(!debtors[di].amount)di++}$("#settlement-list").innerHTML=payments.length?payments.map(payment=>`<div class="settlement"><div><strong>${escapeHtml(payment.from)}</strong><span>pays</span><strong>${escapeHtml(payment.to)}</strong></div><b>${money(payment.amount)}</b></div>`).join(""):`<div class="all-set"><span>✓</span><p>${group.expenses.some(expense=>!expense.isDraft)?"Everyone is settled up.":"Settlements will appear here."}</p></div>`}

$("#group-form").addEventListener("submit",createGroup);$("#group-name").addEventListener("input",()=>hideError("#group-error"));$("#new-group-button").addEventListener("click",()=>showSetup());$("#cancel-group").addEventListener("click",showGroups);$("#back-to-groups").addEventListener("click",showGroups);$("#home-button").addEventListener("click",()=>state.groups.length?showGroups():showSetup());$("#add-test-day").addEventListener("click",()=>{const group=currentGroup();group.testOffset=(group.testOffset||0)+1;selectedDayDate=null;saveState();renderTrip()});$("#modal-backdrop").addEventListener("click",closeExpenseForm);$("#cancel-expense").addEventListener("click",closeExpenseForm);$("#expense-form").addEventListener("submit",addExpense);$("#save-draft-button").addEventListener("click",saveDraft);$("#expense-amount").addEventListener("input",handleExpenseAmountChange);$("#delete-backdrop").addEventListener("click",closeDeleteModal);$("#cancel-delete").addEventListener("click",closeDeleteModal);$("#confirm-delete").addEventListener("click",confirmDelete);document.addEventListener("keydown",event=>{if(event.key!=="Escape")return;if(!$("#delete-modal").hidden)closeDeleteModal();else if(!$("#expense-modal").hidden)closeExpenseForm()});
$("#relation-backdrop").addEventListener("click",closeRelationSummary);$("#close-relation").addEventListener("click",closeRelationSummary);document.addEventListener("keydown",event=>{if(event.key==="Escape"&&!$("#relation-modal").hidden)closeRelationSummary()});
$("#previous-day").addEventListener("click",()=>moveCarousel(-1));$("#next-day").addEventListener("click",()=>moveCarousel(1));const viewport=$(".day-viewport");viewport.addEventListener("touchstart",event=>{swipeStartX=event.changedTouches[0].clientX},{passive:true});viewport.addEventListener("touchend",event=>{if(swipeStartX===null)return;const distance=event.changedTouches[0].clientX-swipeStartX;if(Math.abs(distance)>45)moveCarousel(distance<0?1:-1);swipeStartX=null},{passive:true});window.addEventListener("resize",()=>{if(!$("#group-screen").hidden)updateCarousel()});
attachMoneyInput($("#expense-amount"));
document.querySelectorAll("[data-trip-view]").forEach(button=>button.addEventListener("click",()=>setTripView(button.dataset.tripView)));

function initializeApp(){const saved=dataStore.load();state.groups=saved.groups||[];state.groups.forEach(group=>{group.expenses=group.expenses||[];group.testOffset=group.testOffset||0;group.expenses.forEach(expense=>{if(!expense.shares&&expense.participantIds?.length){const base=Math.floor(expense.amount/expense.participantIds.length),remainder=expense.amount-base*expense.participantIds.length;expense.shares=expense.participantIds.map((id,index)=>({id,amount:base+(index<remainder?1:0)}))}})});if(state.groups.length)showGroups();else{renderPeopleInputs();$("#setup-screen").hidden=false}}
initializeApp();
